import { INodeTypeDescription, NodeConnectionType } from "n8n-workflow";

export const formTriggerDescription: INodeTypeDescription = {
  displayName: 'Multistep Form Trigger',
  name: 'formTrigger',
  icon: 'file:./resources/n8n_custom_forms_icon.svg',
  group: ['trigger'],
  version: 1.0,
  description: 'Trigger node for creating dynamic multi-step forms',
  defaults: {
    name: 'Multistep Form Trigger',
  },
  inputs: [],
  outputs: ['main' as NodeConnectionType],
  webhooks: [
    {
      name: 'default',
      httpMethod: 'GET',
      path: 'form',
      isUrlAutoGenerated: true,
      isForm: true,
    },
  ],
  properties: [
    {
      displayName: 'Form Name',
      name: 'formName',
      type: 'string',
      default: 'My Form',
      description: 'The name of the form',
    },
    {
      displayName: 'Form Inputs',
      name: 'formInputs',
      type: 'fixedCollection',
      typeOptions: {
        multipleValues: true,
      },
      placeholder: 'Add Input',
      default: {},
      options: [
        {
          name: 'formInput',
          displayName: 'Input',
          values: [
            {
              displayName: 'Name',
              name: 'formInputName',
              type: 'string',
              default: '',
              description: 'The name of the input field',
            },
            {
              displayName: 'Label',
              name: 'formInputLabel',
              type: 'string',
              default: '',
              description: 'The label for the input field',
            },
            {
              displayName: 'Type',
              name: 'formInputType',
              type: 'options',
              options: [
                {
                  name: 'Text',
                  value: 'text',
                  description: 'Text input',
                },
                {
                  name: 'Email',
                  value: 'email',
                  description: 'Email input',
                },
                {
                  name: 'Number',
                  value: 'number',
                  description: 'Number input',
                },
                {
                  name: 'Textarea',
                  value: 'textarea',
                  description: 'Textarea input',
                },
              ],
              default: 'text',
              description: 'The type of the input field',
            },
            {
              displayName: 'Required',
              name: 'formInputRequired',
              type: 'boolean',
              default: false,
              description: 'Whether the input field is required',
            },
          ],
        },
      ],
      description: 'Define the inputs for this step',
    },
  ],
};
